### ISSUE TITLE
Research Economics of Urefs

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/roadmap#146]
Cost is set based on the URef lifetime requested (more eras, more cost); economics will be set to motivate cost effective usage: longer lifetimes are more expensive because they are held in global state longer.
Must handle refreshing lifetimes (more cost?)

**Comment by AlexanderLimonov** [comment]
Will treat as a preliminary eval ticket (i.e., looking up how ETH dealt with their old system), taking off @mpapierski for now
