### ISSUE TITLE
Include the protocol version in TransactionV1

### ISSUE THREAD

**Issue by rafal-ch** [casper-network/roadmap#161]
deploys will be used to guide the ee to use the appropriate protocol and or VM so that during 2.0 we can support the legacy protocol and the 2.0 protocol before they are retired in 3.0.   This field will be used by the ee to determine which protocol to execute.   However, before proceeding, confirm with @AlexanderLimonov and @EdHastingsCasperLabs.

**Comment by RitaMAllenCA** [comment]
@AlexanderLimonov do we still need this change? It did not come up in a larger discussion around deploy changes.

**Comment by EdHastingsCasperAssociation** [comment]
This is incorrect. I'll provide guidance during the work week.
