### ISSUE TITLE
add one-time upgrade logic to migrate existing Bids to new ValidatorBid + Delegator structure

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/roadmap#195]

**Comment by RitaMAllenCA** [comment]
@sai - please confirm with @EdHastingsCasperAssociation that this has been completed.  It is part of the epic but was not checked off as complete.  I expect it is a bookkeeping issue.

**Comment by devendran-m** [comment]
Done. Link the PR if possible.

**Comment by devendran-m** [comment]
Related [PR#4196](https://github.com/casper-network/casper-node/pull/4196)
