### ISSUE TITLE
Identity based execution

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/roadmap#200]
Add whitelist/[explore]blacklist powered "Identity" variant to EntryPointAccess and enforce host side

- Blacklisting should inspect the whole callstack. Whitelisting should inspect the immediate caller.
- Mark Greenslade will prepare a case study for the blacklist scenario.

[Story]: Entrypoint identification of the caller.

**Comment by devendran-m** [comment]
As per the outcome from the Sprint Planning on 3rd Oct;
- It was cut from the current VM but included in the new VM. Therefore closing it as done.
