### ISSUE TITLE
Introduce new, bounded length event type

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/roadmap#201]
Create a new bounded length event type
This type supports the ability to record events generated by a contract, and the necessary detail the contract event wants to preserve.  Different contracts will record different events, so the type must be flexible enough to support all types of event recording (string?).  The type will be used to send contract event information to the host.

**Comment by SaiProServ** [comment]
This is an implementation detail which is being addressed as part of the newly created tickets.
