### ISSUE TITLE
Update EE to handle TransactionV1s pt. Deux

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/roadmap#212]
EE should be updated to be able to execute TransactionV1s where these can be equated to an equivalent existing Deploy flow.  We can temporarily return an error immediately for transaction types which cannot currently be handled without heavy work in EE. We want EE to deal with the casper-types TransactionV1 type; they shouldn't be mapped into an EE type as currently happens with Deploy -> DeployItem.  This might need an EE enum type for now (until node 3.0) which has either a DeployItem or a TransactionV1.

**Comment by mpapierski** [comment]
Working on implementation. I'm focusing on integrating native transfer with `TransactionV1` type with testing framework support etc. Once that done, I'll apply same logic and implement other transaction types one by one

- [x] *WIP* `NativeTransaction::MintTransfer`
- [ ] `NativeTransaction::Auction`
- [ ] `NativeTransaction::Reservation` (will error out, we can't currently support this; will ticket it once I have initial integration with other variants working)
- [ ] `UserlandTransactionV1::Standard` - aka session code
- [ ] `UserlandTransactionV1::InstallerUpgrader` - will error out, as described in this ticket we can't support it without heavy work
- [ ] `UserlandTransactionV1::DirectCall`
- [ ] `UserlandTransactionV1::Noop`
- [ ] `UserlandTransactionV1::Closed`  - will error out, as described in this ticket we can't support it without heavy work

**Comment by rafal-ch** [comment]
@SaiProServ @mpapierski @Fraser999 @EdHastingsCasperAssociation 

According to the discussion on the standup, we're putting this task on-hold because it was not clear, whether:
1. this work is needed at all
2. this may be a duplication of what Ed is already doing

**Comment by rafal-ch** [comment]
Clarification:
1. first part of this is tracked via https://github.com/casper-network/casper-node/issues/4340
2. second part (if needed) will be tracked as a new ticket

Also, this is not the duplication of what Ed is doing, that's a separate effort.

We can close this ticket.

cc: @SaiProServ @Fraser999 @mpapierski

**Comment by rafal-ch** [comment]
@SaiProServ @cspramit Can we close this? (see previous comment)

**Comment by cspramit** [comment]
Based on conversation earlier with @SaiProServ , this was planned work, however if in between it was decided as not being needed right now we can keep it  open till the end of sprint and make a call at grooming
