### ISSUE TITLE
Make further additions to the current CEP documentation

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/roadmap#224]
The purpose of this ticket is to make further additions to the CEP documented in [#204](https://app.zenhub.com/workspaces/core-protocol-60953fafb1945f0011a3592d/issues/gh/casper-network/roadmap/204url)

**Comment by alsrdn** [comment]
https://github.com/casper-network/ceps/pull/88/commits/afaf653819ca6db9bf68415586ffd93aec2dd8a8
