### ISSUE TITLE
Test and optimise the URef 2.0 migration

### ISSUE THREAD

**Issue by SaiProServ** [casper-network/roadmap#226]
The URef migration as implemented in the initial PR for feat-uref-2 cannot be run in increments and it can potentially take a very long time to complete. We should test it for both correctness and performance with casper-db-utils and a mainnet snapshot and depending on how long it takes we might want to look into optimising that by finding a way to run it in increments, making it migrate records lazily or use some other optimisation.

**Comment by rafal-ch** [comment]
Unassigning @jacek-casper as he switches to other tasks.

**Comment by devendran-m** [comment]
Won't do, because the feature got cut.
