### ISSUE TITLE
Auction contract improvements

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/roadmap#35]

**Comment by piotr-dziubecki** [comment]
CC @MParlikar

**Comment by goral09** [comment]
We need to make sure that redelgation respects the auction delay - i.e. that it doesn't move tokens immediately, or even at the end of the era in which the request was made. It has to take effect only after period as regular delegate calls. /cc @AlexanderLimonov

**Comment by AlexanderLimonov** [comment]
I'm of two minds on this. On the one hand, more fluid redelegation (no delay) would make it easier for users to shift to smaller validators, if they choose to compete on rates (also a double edged sword, however), but it would also make it potentially easier for large validators to coordinate strategic auction behavior (splitting). Overall, out of caution, I prefer keeping the delay.

**Comment by goral09** [comment]
The delay stays though. With `redelegation` delegator only needs one command to move stake between. I don't think it affects the security at all (the delay is so small anyway - the difference would be 1 era really, 2 hours) but improves the UX.

**Comment by AlexanderLimonov** [comment]
Well, the delay should probably increase at some point. We're in agreement here - keep the delay.

**Comment by goral09** [comment]
It's not about getting rid of the delay. A `redelegate` command won't take effect immediately. It will go to the bonding queue (just like the original `delegate` command would), and take effect only after `auction_delay` eras. The only thing that changes is that the issuer of the command doesn't have to first send `undelegate`, wait `unbonding_delay` eras and then `delegate` and wait `auction_delay`.

**Comment by AlexanderLimonov** [comment]
Yes, I understand. I just brought up the considerations around the delay issue because you mentioned it.

**Comment by GuybrushX** [comment]
@piotr-dziubecki Did you really mean 202_0_ Q4? I think it should be 202_1_, shouldn't it?
