### ISSUE TITLE
ChainWatch dapp

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/roadmap#50]
### Summary
A user-facing application to monitor the state of the network and the on-chain assets. 

### Details
Monitor staked assets and validators.
Trigger notifications in case the validator has stopped responding.
Display the information about the state of the assets (delegating/undelegating with ETAs)
Ability to stake (?)

### UI/UX
A website with Signer integration.

**Comment by MParlikar** [comment]
Please provide a description.

**Comment by EdHastingsCasperAssociation** [comment]
@RitaMAllenCA this should be moved to the L2 board and put onto the backlog

**Comment by RitaMAllenCA** [comment]
Issue moved to [casper-network/Governance #423](https://github.com/casper-network/Governance/issues/423) via [**Zenhub**](https://www.zenhub.com/)
