### ISSUE TITLE
Go-no-Go Mainnet 1.4.3

### ISSUE THREAD

**Issue by cspramit** [casper-network/roadmap#82]
### Mainnet Release Acceptance Criteria. 
Please go though the release acceptance criteria [(here)](https://github.com/casper-network/casper-node/wiki/GnG-Memo-Mainnet-Upgrade-1.4.3) for the upgrade of v1.4.3 to the mainnet of the Casper network.

**Comment by cspramit** [comment]
### Mainnet Release Acceptance Criteria. 
Please go though the release [acceptance()](url) criteria for the upgrade of v1.4.3 to the mainnet of the Casper network.

**Comment by KillianH** [comment]
CasperHolders is updated and live for 1.4.3

**Comment by RBYGLLS** [comment]
Civic confirmed : "we are using Casper-js-sdk v2.7.3. This is the only casper library we are using."

**Comment by RBYGLLS** [comment]
Metacask confirmed "Ready, on 2.7.x"

**Comment by ihor** [comment]
Make Software and CSPR.live are ready for 1.4.3
